export const sampleDesign = {
  id: "GaPC3PIDfTdi5HoDvJnyq",
  type: "GRAPHIC",
  name: "Untitled Design",
  frame: { width: 1200, height: 1200 },
  scenes: [
    {
      id: "p7mc-DKP8a0vR6fCpv-Fd",
      layers: [
        {
          id: "background",
          name: "Initial Frame",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 0,
          top: 0,
          width: 1200,
          height: 1200,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "Background",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: {
            color: "#fcfcfc",
            blur: 4,
            offsetX: 0,
            offsetY: 0,
            affectStroke: false,
            nonScaling: false,
          },
          fill: "#ffffff",
          metadata: {},
        },
        {
          id: "-5rL7f638TV48TB7m8QiM",
          name: "StaticImage",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 120,
          top: 120,
          width: 1300,
          height: 1300,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 0.74,
          scaleY: 0.74,
          type: "StaticImage",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: null,
          src: "https://images.pexels.com/photos/789555/pexels-photo-789555.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          cropX: 0,
          cropY: 0,
          metadata: {},
        },
      ],
      name: "Untitled design",
    },
  ],
  metadata: {},
  previews: [],
}
